kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: python:3
    commands:
      - pip3 install --upgrade pip setuptools wheel requests
      - echo hello
      - echo world
      - python hello.py
  #      - python test.py
  - name: notification
    image: rmilewski/drone-rocket:latest
    when:
      status: [success, failure]
    settings:
      webhook:
        from_secret: "https://rocket.hyperios.space/hooks/65398b8e33c299ed89abc20c/chtNrvpjqx4vjQYL2KpcuTDr7RDHSu6W6SAJzdL9c7QAjwf8"
      channel: devops_alerts
      username: DroneCI
      color:
        - value: green
          when:
            DRONE_BUILD_STATUS: success
        - value: red
          when:
            DRONE_BUILD_STATUS: failure
      message:
        - value: "Build: ${DRONE_BUILD_NUMBER} succeeded!"
          when:
            DRONE_BUILD_STATUS: success
        - value: "Build: ${DRONE_BUILD_NUMBER} failed!"
      fields:
        - title: Author
          value: ${DRONE_COMMIT_AUTHOR}
