kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: python:3
    commands:
      - echo hello
      - echo world
      - python hello.py
trigger:
  event:
    - cron
  cron:
    - hourly
