kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: python:3
    commands:
      - pip3 install --upgrade pip setuptools wheel requests
      - echo hello
      - echo world
      - python hello.py
