kind: pipeline
type: docker
name: default


steps:
  - name: greeting
    image: python:3
    commands:
      - pip3 install -r requirements.txt
      - coverage run -m pytest
  - name: codecov
    image: robertstettner/drone-codecov
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    settings:
      token: ${CODECOV_TOKEN}
      debug: true
      

  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: rocketchat_drone_webhook
      template: >
        {
          "text": "Build ${DRONE_BUILD_NUMBER} ${DRONE_BUILD_STATUS}: ${DRONE_BUILD_LINK}"
        }
