kind: pipeline
type: docker
name: default

environment:
  CODECOV_TOKEN:
    from_secret: codecov_token

steps:
  - name: greeting
    image: python:3
    commands:
      - pip3 install -r requirements.txt
      - pytest --cov .
      - echo $CODECOV_TOKEN
  - name: codecov
    image: robertstettner/drone-codecov

    settings:
      token: ${CODECOV_TOKEN}

  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: rocketchat_drone_webhook
      template: >
        {
          "text": "Build ${DRONE_BUILD_NUMBER} ${DRONE_BUILD_STATUS}: ${DRONE_BUILD_LINK}"
        }
