kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: python:3
    commands:
      - pip3 install -r requirements.txt
      - pytest --cov .
  - name: codecov
    image: robertstettner/drone-codecov
    settings:
      token:
        from_secret: codecov_token

  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: rocketchat_drone_webhook
      template: >
        {
          "text": "Build ${DRONE_BUILD_NUMBER} ${DRONE_BUILD_STATUS}: ${DRONE_BUILD_LINK}"
        }
