kind: pipeline
type: docker
name: default


steps:
  - name: greeting
    image: python:3
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - pip3 install -r requirements.txt
      - pytest --cov app
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov -t ${CODECOV_TOKEN}
  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: rocketchat_drone_webhook
      template: >
        {
          "text": "Build ${DRONE_BUILD_NUMBER} ${DRONE_BUILD_STATUS}: ${DRONE_BUILD_LINK}"
        }
