kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: python:3
    commands:
      - pip3 install --upgrade pip setuptools wheel requests
      - echo hello
      - echo world
      - python hello.py
      - python test.py
  - name: send rocketchat notification
    image: plugins/webhook
    settings:
      urls: https://rocket.hyperios.space/hooks/65398b8e33c299ed89abc20c/chtNrvpjqx4vjQYL2KpcuTDr7RDHSu6W6SAJzdL9c7QAjwf8
      debug: true
      template: |
        {
          "text": "{{ repo.name }} build status: {{ build.status }}",
        }
